# Generated by Django 4.1.1 on 2022-09-14 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wv', '0002_rename_name_wvquotes_speaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(max_length=200, unique=True)),
                ('quote', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='wvQuotes',
        ),
    ]
