# Generated by Django 4.1.1 on 2022-09-14 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wv', '0004_rename_quote_wandavisionquotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wandavisionquotes',
            name='speaker',
            field=models.CharField(max_length=200),
        ),
    ]
