# Generated by Django 4.1.1 on 2022-09-14 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wv', '0005_alter_wandavisionquotes_speaker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wandavisionquotes',
            old_name='speaker',
            new_name='name',
        ),
    ]
